
version: "3"
services:
  web:
    build: .
    command: python manage.py runserver
    volumes:

      - ./:/usr/src/app/
    ports:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: django
      MYSQL_USER: root
      MYSQL_PASSWORD: whdgns1002@
      MYSQL_ROOT_PASSWORD: whdgns1002@
    volumes:
      - mysql_data:/data/mysql/db:/usr/src/minesql
    ports:
      - "3306"
volumes:
  mysql_data:





#version: '3'
#
#services:
#
#    web:
#        build: .
#        command: python manage.py runserver 0.0.0.0:8000  #second_django_prj.wsgi:application --bind 0.0.0.0:8000
#
#        volumes
##            - static_volume:/usr/src/app/_static
##            - media_volume:/usr/src/app/_media
#            - ./:/usr/src/app/
#        ports:
#            - 8000:8000
#
##        depends_on:
##            - db
#        env_file:
#            -   ./.env.dev
#    db:
#        image: mysql:8.0.24
#        environment:
#            - MYSQL_DB=django
#            - MYSQL_USER=root@
#            - MYSQL_PASSWORD=password
#            - MYSQL_ROOT_PASSWORD=whdgns1002@
#
#        volumes:
#            - /data:/var/lib/minesql/data/
#
#volumes:
#    data:

    #    nginx:
    #        build: ./nginx
    #        volumes:
    #            - static_volume:/usr/src/app/_static
    #            - media_volume:/usr/src/app/_media
    #
    #        ports:
    #            - 80:80
    #
    #        depends_on:
    #            - web
#        depends_on:
#            - db
#    db:
#        image: mysql
#        volumes:
#            - mysql_data:/var/lib/mysql/data/
#        env_file:
#            - ./.env.prod.db
#
#
#volumes:
#    mysql_data:
#    static_volume:
#    media_volume: