# Generated by Django 3.2.5 on 2021-07-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_busanann_incheonann_ulsanann_yeosuann'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busanann',
            name='title',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='daumnews',
            name='title',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='incheonann',
            name='title',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ulsanann',
            name='title',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='yeosuann',
            name='title',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
